# Generated by Django 4.2 on 2023-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_code', models.CharField(max_length=1000)),
                ('short_code', models.CharField(max_length=1000)),
            ],
        ),
    ]
