# Generated by Django 4.2 on 2023-04-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='long_code',
            new_name='long_url',
        ),
    ]
