# Generated by Django 4.2 on 2023-04-07 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_long_code_conversion_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
    ]
