# Generated by Django 4.2 on 2023-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_remove_conversion_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='return_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
