# Generated by Django 4.2 on 2023-04-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_conversion_return_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='return_url',
        ),
    ]
