# Generated by Django 4.2 on 2023-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('cohort', models.CharField(max_length=25, verbose_name='cohort')),
                ('favorite_topic', models.CharField(max_length=200, verbose_name='favorite topic')),
                ('favorite_teacher', models.CharField(max_length=20, verbose_name='favorite teacher')),
                ('capstone', models.URLField(verbose_name='capstone project')),
            ],
        ),
    ]
