# Generated by Django 4.2 on 2023-04-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0003_urlshorten_last_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_by', models.CharField(default='not_available', max_length=30, verbose_name='accessed by')),
                ('use_count', models.IntegerField(default=0)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshort.urlshorten')),
            ],
        ),
    ]
