# Generated by Django 4.2 on 2023-04-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
