# Generated by Django 4.2 on 2023-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=280)),
                ('pub_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
