# Generated by Django 4.2 on 2023-04-05 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 23, 19, 16, 860068, tzinfo=datetime.timezone.utc), verbose_name='completed date'),
        ),
    ]
